=== x0xe/HolaMundo/XML/XML con DTD/preguntes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT preguntes (pregunta)+>
<!ELEMENT pregunta (tipo,título,texto,opción*,respuesta)>
<!ATTLIST pregunta id ID #REQUIRED>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT título (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT opción (#PCDATA)>
<!ELEMENT respuesta (#PCDATA)>
<!ELEMENT radio (#PCDATA)>

=== x0xe/HolaMundo/XML/preguntes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE preguntes SYSTEM "preguntes.dtd">
<preguntes>
<pregunta id='preg1'>
<tipo>texto</tipo>
<título>Pregunta Asignatura</título>
<texto>Como se llama esta asignatura?</texto>
<respuesta>Lenguaje de Marcas y Sistemas de Gestión de la Información</respuesta>
</pregunta>

<pregunta id='preg2'>
<tipo>select</tipo>
<título> Número de archivos</título>
<texto>Cuántos archivos tiene esta entrega?</texto>
<opción>2</opción>
<opción>1</opción>
<opción>3</opción>
<respuesta>1</respuesta>
</pregunta>

<pregunta id='preg3'>
<tipo>select</tipo>
<título> Fichero HTML </título>
<texto>Es posible abrir un fichero .html en Google chrome?</texto>
<opción>No</opción>
<opción>Si</opción> 
<respuesta>1</respuesta> 
</pregunta>

<pregunta id='preg4'>
<tipo>texto</tipo>
<título> Web </título>
<texto>Cómo se llama la web dónde colgamos las tareas?</texto>
<respuesta> www.GitHub.com </respuesta>
</pregunta>

<pregunta id='preg5'>
<tipo>radio</tipo>
<título> suma </título>
<texto> Cúanto son 2+2? </texto>
<opción> 4 </opción>
<opción> 3 </opción>
<respuesta> 0 </respuesta>
</pregunta>

</preguntes>

=== x0xe/HolaMundo/preguntes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE preguntes SYSTEM "preguntes.dtd">
<preguntes>
<pregunta id='preg1'>
<tipo>texto</tipo>
<texto>Como se llama esta asignatura?</texto>
<respuesta>Lenguaje de Marcas y Sistemas de Gestión de la Información</respuesta>
</pregunta>

<pregunta id='preg2'>
<tipo>select</tipo>
<texto>Cuántos archivos tiene esta entrega?</texto>
<opción>2</opción>
<opción>1</opción>
<opción>3</opción>
<respuesta>1</respuesta>
</pregunta>

<pregunta id='preg3'>
<tipo>select</tipo>
<texto>Es posible abrir un fichero .html en Google chrome?</texto>
<opción>No</opción>
<opción>Si</opción> 
<respuesta>1</respuesta> 
</pregunta>

<pregunta id='preg4'>
<tipo>texto</tipo>
<texto>Cómo se llama la web dónde colgamos las tareas?</texto>
<respuesta> www.GitHub.com </respuesta>
</pregunta>

<pregunta id='preg5'>
<tipo>radio</tipo>
<texto> Cúanto son 2+2? </texto>
<opción> 4 </opción>
<opción> 3 </opción>
<respuesta> 0 </respuesta>
</pregunta>

</preguntes>
