=== x0xe/HolaMundo/XML/XML con XSD/preguntas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="questions">
<xs:complexType>
<xs:sequence>
<xs:element name="question" maxOccurs="10" minOccurs="0">
 <xs:complexType>
  <xs:sequence>
   <xs:element name="type">
   <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="texto"/>
      <xs:enumeration value="select"/>
      <xs:enumeration value="radio"/>
      <xs:enumeration value="checkbox"/>
      <xs:enumeration value="number"/>
    </xs:restriction>
   </xs:simpleType>
   </xs:element>
   <xs:element type="xs:string" name="title"/>
   <xs:element type="xs:string" name="text"/>
   <xs:element type="xs:string" name="option" maxOccurs="unbounded" minOccurs="0"/>
   <xs:element type="xs:string" name="answer" maxOccurs="unbounded" minOccurs="1"/>
  </xs:sequence>
  <xs:attribute type="xs:string" name="id" use="required"/>
 </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== x0xe/HolaMundo/XML/XML con XSD/preguntas.xml
<?xml version="1.0" encoding="UTF-8"?>
<questions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="preguntas.xsd">

<question id="preg1">
<type>texto</type>
<title>Pregunta Asignatura</title>
<text>Cómo se llama esta asignatura?</text>
<answer>Lenguaje de Marcas y Sistemas de Gestión de la Información</answer>
</question>

<question id="preg2">
<type>select</type>
<title>Número de archivos</title>
<text> Cuántos archivos tiene esta entrega? </text>
<option>1</option>
<option>2</option>
<option>3</option>
<answer>1</answer>
</question>

<question id="preg3">
<type>select</type>
<title>Fichero html</title>
<text> Es posible abrir un fichero .html en Google chrome?</text>
<option>No</option>
<option>Sí</option>
<answer>1</answer>
</question>

<question id="preg4">
<type>texto</type>
<title>web</title>
<text> Cómo se llama la web dónde colgamos las tareaS?</text>
<answer> www.github.com </answer>
</question>

<question id='preg5'>
<type>radio</type>
<title> suma </title>
<text> Cúanto son 2+2? </text>
<option> 4 </option>
<option> 3 </option>
<answer> 0 </answer>
</question>

<question id="preg6">
<type>checkbox</type>
<title>múltiple</title>
<text>Marca los distintos archivos vistos en esta asignatura </text>
<option>html</option>
<option>mp3</option>
<option>js</option>
<option>iso</option>
<answer>0</answer>
<answer>2</answer>
</question>

<question id="preg7">
<type>checkbox</type>
<title>Selecciona una o más</title>
<text>Cual de los siguientes archivos puede crearse funcionalmente sin necesidad de otro?</text>
<option>.js</option>
<option>.hmtl</option>
<option>.xml</option>
<option>.xsd</option>
<answer>1</answer>
<answer>2</answer>
</question>

<question id='preg8'>
<type>radio</type>
<title> XML </title>
<text> Qué quiere decir XML? </text>
<option> eXtensible Markup Language </option>
<option> eXtensible Meta Language </option>
<option> eXpansible Markup Language</option>
<answer> 0 </answer>
</question>

<question id='preg9'>
<type>number</type>
<title>año</title>
<text>En qué año estamos? </text>
<answer> 2017 </answer>
</question>

<question id='preg10'>
<type>number</type>
<title>FP</title>
<text>Cuántos años dura este FP a distancia?</text>
<answer> 2 </answer>
</question>

</questions>

=== x0xe/HolaMundo/XML/FINAL/XML/preguntas.xml
<?xml version="1.0" encoding="UTF-8"?>
<questions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="preguntas.xsd">


<question id="preg1">
<type>select</type>
<title>Selecciona la opción correcta</title>
<text>Cuántos archivos con extensión ".html" tiene esta entrega?</text>
<option>1</option>
<option>2</option>
<option>3</option>
<answer>1</answer>
</question>

<question id="preg2">
<type>select</type>
<title>Fichero html en navegador</title>
<text>Es posible abrir un fichero con extensión ".html" en Firefox?</text>
<option>Sí</option>
<option>No</option>
<option>Depende de la versión de que dispongamos</option>
<answer>0</answer>
</question>

<question id="preg3">
<type>texto</type>
<title>Adivina el color</title>
<text>De qué color era el caballo blanco de Santiago?</text>
<answer>blanco</answer>
</question>

<question id="preg4">
<type>texto</type>
<title>Página web</title>
<text>Cómo se llama la web dónde colgamos las tareas?(incluir "www.")</text>
<answer>www.github.com</answer>
</question>



<question id="preg5">
<type>checkbox</type>
<title>Selección múltiple</title>
<text>Marca las distintas extensiones de archivos utilizadas en esta asignatura </text>
<option>.html</option>
<option>.mp3</option>
<option>.js</option>
<option>.iso</option>
<answer>0</answer>
<answer>2</answer>
</question>

<question id="preg6">
<type>checkbox</type>
<title>Selecciona una o más</title>
<text>Qué animal o animales tienen cuatro patas?</text>
<option>Araña</option>
<option>Perro</option>
<option>Vaca</option>
<option>Todas las anteriores</option>
<answer>1</answer>
<answer>2</answer>
</question>


<question id='preg7'>
<type>radio</type>
<title>Haz esta cuenta</title>
<text>Cúanto son 11x11?</text>
<option>111</option>
<option>121</option>
<answer>1</answer>
</question>

<question id='preg8'>
<type>radio</type>
<title> Sobre ciencia </title>
<text> Quién formuló la teoria de la relatividad? </text>
<option> Einstein </option>
<option> Tesla </option>
<option> Newton</option>
<answer>0</answer>
</question>

<question id='preg9'>
<type>number</type>
<title>Descubrimiento</title>
<text>En qué año se descubrió América? </text>
<answer>1492</answer>
</question>

<question id='preg10'>
<type>number</type>
<title>Año entrega</title>
<text>En qué año se entrega esta práctica?</text>
<answer>2017</answer>
</question>

</questions>
